import { Josefin_Sans } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";

//imported josefinsans light from google font using next.js built in fonts
const JosefinSans = Josefin_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400"],
});

//imported angella white font downloaded from dafont.
const AngellaWhite = localfont({
  src: [{ path: "../../public/fonts/Angella White.otf" }],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JosefinSans.className}>{children}</body>
    </html>
  );
}
